### ISSUE TITLE
IBM COS Issue with proxy configuration

### ISSUE THREAD

**Issue by bvinoth186** [IBM/ibm-cos-sdk-java#24]
Hi, 

I’m using ibm-cos-java-sdk version 2.5.0.  I’m unable to access the buckets in company vpn. I have tried enabling proxy configuration with both BasicAWSCredentials as well as BasicIBMOAuthCredentials.  I always get authenticationrequired with request id as null.  Same code works well in public network.  I was going through the issues found that this issue was already raised and addressed 2.4.2 release.  Looks like im missing a configuration here. Any inputs would be helpful.  

**Code Snippet :**
```

private AmazonS3 createClient() {	

     //option 1		
     AWSCredentials credentials = new BasicAWSCredentials(accessKey, secretKey);  
     //option 2        	
     AWSCredentials credentials = new BasicIBMOAuthCredentials(apiKey, instaceId); 
     ClientConfiguration clientConfig = new ClientConfiguration().withRequestTimeout(5000);
     clientConfig.setUseTcpKeepAlive(true);
     clientConfig.setProxyHost(proxyHost);
     clientConfig.setProxyPort(proxyPort);

     AmazonS3 cos = AmazonS3ClientBuilder.standard().withCredentials(new AWSStaticCredentialsProvider(credentials))
				.withEndpointConfiguration(new EndpointConfiguration(endpoint, location))
				.withPathStyleAccessEnabled(true).withClientConfiguration(clientConfig).build();

     return cos;
}
```

**Error :** 

`
Caused by: com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: authenticationrequired (Service: Amazon S3; Status Code: 407; Error Code: 407 authenticationrequired; Request ID: null), S3 Extended Request ID: null
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1588)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1258)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1030)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:742)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:716)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:699)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:667)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:649)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:513)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3890)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3837)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3831)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:879)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.listBuckets(AmazonS3Client.java:885)
`
-Vinoth

**Comment by bvinoth186** [comment]
Previous issue on the same subject 

https://github.com/IBM/ibm-cos-sdk-java/issues/12

**Comment by smcgrath-IBM** [comment]
Hi @bvinoth186 the previous issue was specific to IAM authentication & is now resolved. Your issue is different as both authentication mechanisms are failing. 

I think it is environmental, possibly your proxy server is not forwarding authorization headers. Can you get your network team to trace which headers are been sent from your proxy server, compare the difference from the requests sent locally. 

You could also set up a local proxy such as mitmproxy to validate your code is functioning against a proxy which you have admin rights to configure.

**Comment by bvinoth186** [comment]
Hi, Thanks for the update.  It could be our proxy server.  Is there anyway that we could see what is being to sent in logs?  I understand there is proxy server in the middle.  I would want to have the data in hand before i engage our network team.  Any inputs would be helpful.

**Comment by seamy49** [comment]
If you have log4j configured in your classpath you will get SDK logs. But for raw http requests I would recommend a local http sniffer tool or mitm proxy, you will need to use non secure endpoints also unless you install the certs.

**Comment by bvinoth186** [comment]
Thanks I will try with local proxy option and get back here.

**Comment by bvinoth186** [comment]
i'm able to connect to IBM COS via local Fiddler proxy server.  This issue can be closed. Thanks for the support and inputs

**Comment by smcgrath-IBM** [comment]
Thanks for the update
