### ISSUE TITLE
COS client cannot handle common special characters

### ISSUE THREAD

**Issue by pwinckles** [IBM/ibm-cos-sdk-java#28]
The COS client errors out when I try to put objects with keys that contain the `=` character. I understand from the [Amazon documentation](https://docs.aws.amazon.com/AmazonS3/latest/dev/UsingMetadata.html) that there are certain characters that may cause problems. However, the Amazon SDK v1 that your client is a fork of is able to correctly handle the `=` character.

**Comment by pwinckles** [comment]
Here's some additional information. I'm using version 2.6.0 of the client. Here's an example stacktrace:

```
com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 221fdf56-ef75-4bc8-9e99-f70748356631)
, S3 Extended Request ID: null
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1712)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1367)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
	at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3985)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3932)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1683)
	at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:3019)
```

That was produced by executing the following:

```java
ibmClient.putObject(bucket, "0=ocfl_1.0", "testing");
```

There is nothing wrong with the keys. Executing the same request without the `=` works fine.

**Comment by stephenskinner** [comment]
Hi,
I've not been able to reproduce this error, I can successfully run putObject with the key containing an = and get a 200 response.
I can provide some code (with HMAC auth) if you need it. Are you able to provide the code that is throwing an exception?

**Comment by stephenskinner** [comment]
Hi,
The standard putObject is working fine with 2.6.0, can you provide the code you are using to initialise the client please? The error points to an issue with signing the request.

**Comment by pwinckles** [comment]
```java
AmazonS3ClientBuilder.standard()
                .withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretKey)))
                .withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endpoint, "us"))
                .enablePathStyleAccess()
                .build();
```

**Comment by pwinckles** [comment]
The same request works using the same client when there is no `=` in the key.

**Comment by rtveitch** [comment]
The following script appears to work against the `us-south` region, using your suggested client configuration.

```java
public static void main(String args[]) {
		final String accessKey = "<access_key>";
		final String secretKey = "<secret_key>";
		final String endpoint = "s3.us-south.cloud-object-storage.appdomain.cloud";
		final String region = "us-south";
		AmazonS3 s3Client = AmazonS3ClientBuilder.standard()
				.withCredentials(new AWSStaticCredentialsProvider(new BasicAWSCredentials(accessKey, secretKey)))
				.withEndpointConfiguration(new AwsClientBuilder.EndpointConfiguration(endpoint, region))
				.enablePathStyleAccess().build();
		System.out.println("## Starting");
		try {
			System.out.println("## Writing object");
			s3Client.putObject("test-client-java-20200110155619", "0=ocfl_1.0", "testing");

		} catch (Exception e) {
			System.out.println(e);
		}
		System.out.println("## Finished");
	}
```

Output is:

```
## Starting
## Writing object
## Finished
```

<img width="1012" alt="Screen Shot 2020-01-10 at 4 26 24 PM" src="https://user-images.githubusercontent.com/25228001/72190785-09d95280-33c6-11ea-81b0-a03b5f2ec09c.png">

@pwinckles can you compare this against your full script and let us know if you spot any differences? I'm running on Java 8, although I would expect any issue here would be more likely to be related to region, bucket, or otherwise configuration related.

**Comment by pwinckles** [comment]
@rtveitch I'll try it out on Monday. I'll also do a test with Java 8.

One thing to note, I am using an on premise, private cloud storage install and not the public cloud.

**Comment by pwinckles** [comment]
@rtveitch I ran your code (identical except for the different endpoint) and it doesn't work:

```
## Starting
## Writing object
com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details. (Service: Amazon S3; Status Code: 403; Error Code: SignatureDoesNotMatch; Request ID: 0fd76dc8-a341-4339-a5aa-0084143e74a1), S3 Extended Request ID: null
## Finished

```

**Comment by pwinckles** [comment]
I turned on wire logging.

Here is the wire log for the request that does not work:

```
09:01:07.210 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> PUT /[BUCKET]/0=ocfl_1.0 HTTP/1.1
09:01:07.210 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: [ENDPOINT]
09:01:07.210 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> x-amz-content-sha256: UNSIGNED-PAYLOAD
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Authorization: AWS4-HMAC-SHA256 Credential=[ACCESS_KEY]/20200113/us-south/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=539c574ab94ba9635513ed831ece42d98e107692fb7517fb326e1a68f5816830
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> X-Amz-Date: 20200113T150106Z
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: ibm-cos-sdk-java/2.6.0 Linux/3.10.0-1062.9.1.el7.x86_64 OpenJDK_64-Bit_Server_VM/11.0.2+9/11.0.2
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> amz-sdk-invocation-id: a5aaf26b-f929-a383-21cd-479a76fdcc54
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> amz-sdk-retry: 0/0/500
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: text/plain
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 7
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
09:01:07.211 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Expect: 100-continue
09:01:07.211 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "PUT /[BUCKET]/0=ocfl_1.0 HTTP/1.1[\r][\n]"
09:01:07.211 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: [ENDPOINT][\r][\n]"
09:01:07.211 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=[ACCESS_KEY]/20200113/us-south/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=539c574ab94ba9635513ed831ece42d98e107692fb7517fb326e1a68f5816830[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "X-Amz-Date: 20200113T150106Z[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: ibm-cos-sdk-java/2.6.0 Linux/3.10.0-1062.9.1.el7.x86_64 OpenJDK_64-Bit_Server_VM/11.0.2+9/11.0.2[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-invocation-id: a5aaf26b-f929-a383-21cd-479a76fdcc54[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-retry: 0/0/500[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: text/plain[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 7[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
09:01:07.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
09:01:07.213 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
09:01:07.228 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 403 Forbidden[\r][\n]"
09:01:07.228 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Mon, 13 Jan 2020 15:01:04 GMT[\r][\n]"
09:01:07.228 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Clv-Request-Id: 2dd4fad5-c978-46fe-b3e4-afe4d4066feb[\r][\n]"
09:01:07.228 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: 3.14.1.60[\r][\n]"
09:01:07.228 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Clv-S3-Version: 2.5[\r][\n]"
09:01:07.228 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "x-amz-request-id: 2dd4fad5-c978-46fe-b3e4-afe4d4066feb[\r][\n]"
09:01:07.228 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Type: application/xml[\r][\n]"
09:01:07.228 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 3536[\r][\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Connection: close[\r][\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Error><Code>SignatureDoesNotMatch</Code><Message>The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.</Message><Resource>/[BUCKET]/0=ocfl_1.0</Resource><RequestId>2dd4fad5-c978-46fe-b3e4-afe4d4066feb</RequestId><StringToSign>AWS4-HMAC-SHA256[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "20200113T150106Z[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "20200113/us-south/s3/aws4_request[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "812c783d05dfe5a18b4c1c5aa7e42de29169f375e2ebf538ace4ff3121c69745</StringToSign><StringToSignBytes>65 87 83 52 45 72 77 65 67 45 83 72 65 50 53 54 10 50 48 50 48 48 49 49 51 84 49 53 48 49 48 54 90 10 50 48 50 48 48 49 49 51 47 117 115 45 115 111 117 116 104 47 115 51 47 97 119 115 52 95 114 101 113 117 101 115 116 10 56 49 50 99 55 56 51 100 48 53 100 102 101 53 97 49 56 98 52 99 49 99 53 97 97 55 101 52 50 100 101 50 57 49 54 57 102 51 55 53 101 50 101 98 102 53 51 56 97 99 101 52 102 102 51 49 50 49 99 54 57 55 52 53</StringToSignBytes><SignatureProvided>539c574ab94ba9635513ed831ece42d98e107692fb7517fb326e1a68f5816830</SignatureProvided><CanonicalRequest>PUT[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "/[BUCKET]/0=ocfl_1.0[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "amz-sdk-invocation-id:a5aaf26b-f929-a383-21cd-479a76fdcc54[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "amz-sdk-retry:0/0/500[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "content-length:7[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "content-type:text/plain[\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "host:[ENDPOINT][\n]"
09:01:07.229 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "user-agent:ibm-cos-sdk-java/2.6.0 Linux/3.10.0-1062.9.1.el7.x86_64 OpenJDK_64-Bit_Server_VM/11.0.2+9/11.0.2[\n]"
09:01:07.230 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "x-amz-content-sha256:UNSIGNED-PAYLOAD[\n]"
09:01:07.230 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "x-amz-date:20200113T150106Z[\n]"
09:01:07.230 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\n]"
09:01:07.230 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date[\n]"
09:01:07.230 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "UNSIGNED-PAYLOAD</CanonicalRequest><CanonicalRequestBytes>80 85 84 10 47 100 99 99 45 112 114 101 115 101 114 118 97 116 105 111 110 45 116 101 115 116 45 48 49 47 48 61 111 99 102 108 95 49 46 48 10 10 97 109 122 45 115 100 107 45 105 110 118 111 99 97 116 105 111 110 45 105 100 58 97 53 97 97 102 50 54 98 45 102 57 50 57 45 97 51 56 51 45 50 49 99 100 45 52 55 57 97 55 54 102 100 99 99 53 52 10 97 109 122 45 115 100 107 45 114 101 116 114 121 58 48 47 48 47 53 48 48 10 99 111 110 116 101 110 116 45 108 101 110 103 116 104 58 55 10 99 111 110 116 101 110 116 45 116 121 112 101 58 116 101 120 116 47 112 108 97 105 110 10 104 111 115 116 58 115 51 46 100 114 105 118 101 46 119 105 115 99 46 101 100 117 10 117 115 101 114 45 97 103 101 110 116 58 105 98 109 45 99 111 115 45 115 100 107 45 106 97 118 97 47 50 46 54 46 48 32 76 105 110 117 120 47 51 46 49 48 46 48 45 49 48 54 50 46 57 46 49 46 101 108 55 46 120 56 54 95 54 52 32 79 112 101 110 74 68 75 95 54 52 45 66 105 116 95 83 101 114 118 101 114 95 86 77 47 49 49 46 48 46 50 43 57 47 49 49 46 48 46 50 10 120 45 97 109 122 45 99 111 110 116 101 110 116 45 115 104 97 50 53 54 58 85 78 83 73 71 78 69 68 45 80 65 89 76 79 65 68 10 120 45 97 109 122 45 100 97 116 101 58 50 48 50 48 48 49 49 51 84 49 53 48 49 48 54 90 10 10 97 109 122 45 115 100 107 45 105 110 118 111 99 97 116 105 111 110 45 105 100 59 97 109 122 45 115 100 107 45 114 101 116 114 121 59 99 111 110 116 101 110 116 45 108 101 110 103 116 104 59 99 111 110 116 101 110 116 45 116 121 112 101 59 104 111 115 116 59 117 115 101 114 45 97 103 101 110 116 59 120 45 97 109 122 45 99 111 110 116 101 110 116 45 115 104 97 50 53 54 59 120 45 97 109 122 45 100 97 116 101 10 85 78 83 73 71 78 69 68 45 80 65 89 76 79 65 68</CanonicalRequestBytes><AWSAccessKeyId>[ACCESS_KEY]</AWSAccessKeyId><httpStatusCode>403</httpStatusCode></Error>"
09:01:07.232 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 403 Forbidden
09:01:07.232 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Mon, 13 Jan 2020 15:01:04 GMT
09:01:07.233 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Clv-Request-Id: 2dd4fad5-c978-46fe-b3e4-afe4d4066feb
09:01:07.233 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: 3.14.1.60
09:01:07.233 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Clv-S3-Version: 2.5
09:01:07.233 [main] DEBUG org.apache.http.headers - http-outgoing-0 << x-amz-request-id: 2dd4fad5-c978-46fe-b3e4-afe4d4066feb
09:01:07.233 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Type: application/xml
09:01:07.233 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 3536
09:01:07.233 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Connection: close
```

Here is the wire log for the same request where the object key is URL encoded first (`URLEncoder.encode("0=ocfl_1.0", StandardCharsets.UTF_8`):

```
09:05:49.199 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> PUT /[BUCKET]/0%253Docfl_1.0 HTTP/1.1
09:05:49.199 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Host: [ENDPOINT]
09:05:49.199 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> x-amz-content-sha256: UNSIGNED-PAYLOAD
09:05:49.199 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Authorization: AWS4-HMAC-SHA256 Credential=[ACCESS_KEY]/20200113/us-south/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=844a153ed01d673b8c4ade4f47ec5dd690067e628419c8934ce284f30f335e2e
09:05:49.199 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> X-Amz-Date: 20200113T150548Z
09:05:49.199 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> User-Agent: ibm-cos-sdk-java/2.6.0 Linux/3.10.0-1062.9.1.el7.x86_64 OpenJDK_64-Bit_Server_VM/11.0.2+9/11.0.2
09:05:49.199 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> amz-sdk-invocation-id: 8cd18003-b455-6150-8634-341c5157f783
09:05:49.199 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> amz-sdk-retry: 0/0/500
09:05:49.200 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Type: text/plain
09:05:49.200 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Content-Length: 7
09:05:49.200 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Connection: Keep-Alive
09:05:49.200 [main] DEBUG org.apache.http.headers - http-outgoing-0 >> Expect: 100-continue
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "PUT /[BUCKET]/0%253Docfl_1.0 HTTP/1.1[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: [ENDPOINT][\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=[ACCESS_KEY]/20200113/us-south/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=844a153ed01d673b8c4ade4f47ec5dd690067e628419c8934ce284f30f335e2e[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "X-Amz-Date: 20200113T150548Z[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: ibm-cos-sdk-java/2.6.0 Linux/3.10.0-1062.9.1.el7.x86_64 OpenJDK_64-Bit_Server_VM/11.0.2+9/11.0.2[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-invocation-id: 8cd18003-b455-6150-8634-341c5157f783[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-retry: 0/0/500[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: text/plain[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 7[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
09:05:49.200 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
09:05:49.210 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 100 Continue[\r][\n]"
09:05:49.210 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
09:05:49.212 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 100 Continue
09:05:49.212 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "testing"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Mon, 13 Jan 2020 15:05:46 GMT[\r][\n]"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Clv-Request-Id: 1f21afd6-4a99-4f63-9bbc-25af08676308[\r][\n]"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: 3.14.1.60[\r][\n]"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Clv-S3-Version: 2.5[\r][\n]"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "x-amz-request-id: 1f21afd6-4a99-4f63-9bbc-25af08676308[\r][\n]"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "ETag: "ae2b1fca515949e5d54fb22b8ed95575"[\r][\n]"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
09:05:49.226 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
09:05:49.227 [main] DEBUG org.apache.http.headers - http-outgoing-0 << HTTP/1.1 200 OK
09:05:49.227 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Date: Mon, 13 Jan 2020 15:05:46 GMT
09:05:49.227 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Clv-Request-Id: 1f21afd6-4a99-4f63-9bbc-25af08676308
09:05:49.227 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Server: 3.14.1.60
09:05:49.227 [main] DEBUG org.apache.http.headers - http-outgoing-0 << X-Clv-S3-Version: 2.5
09:05:49.227 [main] DEBUG org.apache.http.headers - http-outgoing-0 << x-amz-request-id: 1f21afd6-4a99-4f63-9bbc-25af08676308
09:05:49.227 [main] DEBUG org.apache.http.headers - http-outgoing-0 << ETag: "ae2b1fca515949e5d54fb22b8ed95575"
09:05:49.227 [main] DEBUG org.apache.http.headers - http-outgoing-0 << Content-Length: 0
```

Probably of most interest is the url. The request that doesn't work is executing `PUT /[BUCKET]/0=ocfl_1.0 HTTP/1.1` and the request that "works" (I don't want the key to be url encoded except during transmission) is executing `PUT /[BUCKET]/0%253Docfl_1.0 HTTP/1.1`.

But, it's sounding like there's something wrong with our cloud install and it's not necessarily a problem with the client library.

**Comment by pwinckles** [comment]
What's the url for your requests that work? It's odd to me that the key `0=ocfl_1.0` is NOT url encoded in my request that fails.

**Comment by rtveitch** [comment]
I think the url encoding might not be the actual problem. Here's the output from my request which succeeds:

```
## Starting
## Writing object
15:12:12.753 [main] DEBUG org.apache.http.client.protocol.RequestAddCookies - CookieSpec selected: default
15:12:12.760 [main] DEBUG org.apache.http.client.protocol.RequestAuthCache - Auth cache not set in the context
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "PUT /[BUCKET]/0=ocfl_1.0 HTTP/1.1[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Host: [ENDPOINT][\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "x-amz-content-sha256: UNSIGNED-PAYLOAD[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Authorization: AWS4-HMAC-SHA256 Credential=[ACCESS_KEY]/20200113/us-south/s3/aws4_request, SignedHeaders=amz-sdk-invocation-id;amz-sdk-retry;content-length;content-type;host;user-agent;x-amz-content-sha256;x-amz-date, Signature=2d4666461a8bf85960e3a7e6d849ddc8af09e35c3fdf2ca883239aa45c08937a[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "X-Amz-Date: 20200113T211212Z[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "User-Agent: ibm-cos-sdk-java/2.6.0 Mac_OS_X/10.14.6 Java_HotSpot(TM)_64-Bit_Server_VM/25.151-b12/1.8.0_151 kotlin/1.3.41-release-150 (1.3.41)[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-invocation-id: 6dd9d17c-e59c-d933-2a84-c093fd0e8f90[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "amz-sdk-retry: 0/0/500[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Type: text/plain[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Content-Length: 7[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Connection: Keep-Alive[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "Expect: 100-continue[\r][\n]"
15:12:12.801 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "[\r][\n]"
15:12:12.869 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 100 Continue[\r][\n]"
15:12:12.870 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
15:12:12.872 [main] DEBUG org.apache.http.wire - http-outgoing-0 >> "testing"
15:12:12.902 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "HTTP/1.1 200 OK[\r][\n]"
15:12:12.903 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Date: Mon, 13 Jan 2020 21:12:12 GMT[\r][\n]"
15:12:12.903 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Clv-Request-Id: 4c4fe76f-d834-4281-b338-ac50165d0d8b[\r][\n]"
15:12:12.903 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Server: Cleversafe/3.14.8.79[\r][\n]"
15:12:12.903 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "X-Clv-S3-Version: 2.5[\r][\n]"
15:12:12.903 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "x-amz-request-id: 4c4fe76f-d834-4281-b338-ac50165d0d8b[\r][\n]"
15:12:12.903 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "ETag: "ae2b1fca515949e5d54fb22b8ed95575"[\r][\n]"
15:12:12.903 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "Content-Length: 0[\r][\n]"
15:12:12.903 [main] DEBUG org.apache.http.wire - http-outgoing-0 << "[\r][\n]"
## Finished
```

**Comment by pwinckles** [comment]
Great, thanks! We'll open a different ticket to try to figure out what's going on with our private cloud.
