### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Ljavax/management/MBeanServerFactory;

### ISSUE THREAD

**Issue by juanlabrador** [IBM/ibm-cos-sdk-java#30]
When init Amazons3Client
````
val clientConfiguration = ClientConfiguration()
clientConfiguration.connectionTimeout = 30000
clientConfiguration.socketTimeout = 30000
val cos = AmazonS3ClientBuilder.standard()
        .withCredentials(AWSStaticCredentialsProvider(BasicIBMOAuthCredentials(apiKey, serviceInstanceId)))
        .withClientConfiguration(clientConfiguration)
        .withEndpointConfiguration(AwsClientBuilder.EndpointConfiguration(Constants.COS.URL, "us-south"))
        .enablePathStyleAccess()
        .build()
return TransferManagerBuilder.standard()
        .withS3Client(cos)
        .build()
````

```
java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/management/MBeanServerFactory;
        at com.ibm.cloud.objectstorage.jmx.MBeans.getMBeanServer(MBeans.java:111)
        at com.ibm.cloud.objectstorage.jmx.MBeans.registerMBean(MBeans.java:50)
        at com.ibm.cloud.objectstorage.jmx.SdkMBeanRegistrySupport.registerMetricAdminMBean(SdkMBeanRegistrySupport.java:27)
        at com.ibm.cloud.objectstorage.metrics.AwsSdkMetrics.registerMetricAdminMBean(AwsSdkMetrics.java:392)
        at com.ibm.cloud.objectstorage.metrics.AwsSdkMetrics.<clinit>(AwsSdkMetrics.java:353)
        at com.ibm.cloud.objectstorage.metrics.AwsSdkMetrics.addAll(AwsSdkMetrics.java:656)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.<clinit>(AmazonS3Client.java:307)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:35)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Builder$1.apply(AmazonS3Builder.java:32)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:64)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3ClientBuilder.build(AmazonS3ClientBuilder.java:28)
        at com.ibm.cloud.objectstorage.client.builder.AwsSyncClientBuilder.build(AwsSyncClientBuilder.java:46)
        at com.taugo.fleets.extensions.ContextKt.transferManagerCOS(Context.kt:136)
        at com.taugo.fleets.reception.form.viewmodel.FormReceptionViewModel.buildReceptionInside(FormReceptionViewModel.kt:425)
        at com.taugo.fleets.reception.form.view.FormReceptionActivity$click$1$2.invokeSuspend(FormReceptionActivity.kt:183)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:56)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7403)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:935)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.management.MBeanServerFactory" on path: DexPathList[[zip file "/data/app/com.taugo.fleet.debug-M2gA_sz-900iNPYlCj4GoA==/base.apk"],nativeLibraryDirectories=[/data/app/com.taugo.fleet.debug-M2gA_sz-900iNPYlCj4GoA==/lib/arm64, /data/app/com.taugo.fleet.debug-M2gA_sz-900iNPYlCj4GoA==/base.apk!/lib/arm64-v8a, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

```

implementation 'com.ibm.cos:ibm-cos-java-sdk-s3:2.6.1'
implementation 'com.ibm.cos:ibm-cos-java-sdk-core:2.6.1'

Thanks!

**Comment by juanlabrador** [comment]
This case  https://stackoverflow.com/questions/58167829/awss3-client-throws-error-on-initialization  but was with AWS, so, no working with COS, but it's the same problem

**Comment by juanlabrador** [comment]
This crashed when AmazonS3ClientBuilder is build().

**Comment by juanlabrador** [comment]
Need support to Android :(

**Comment by rtveitch** [comment]
Yes this SDK does not support Android, only Desktop/Server.
