### ISSUE TITLE
Certificate error causes the token provider to give useless exception stacktrace 

### ISSUE THREAD

**Issue by ifs-gaetanlalanne** [IBM/ibm-cos-sdk-java#44]
https://github.com/IBM/ibm-cos-sdk-java/blob/736bc712488fe31db0ab8fdbb592aca2b1cd813b/ibm-cos-java-sdk-core/src/main/java/com/ibm/cloud/objectstorage/oauth/DefaultTokenProvider.java#L211

When the exception does not have a cause, it prints this :
Caused by: com.ibm.cloud.objectstorage.oauth.OAuthServiceException: null at com.ibm.cloud.objectstorage.oauth.DefaultTokenProvider.retrieveTokenHelper(DefaultTokenProvider.java:211) at com.ibm.cloud.objectstorage.oauth.DefaultTokenProvider.retrieveToken(DefaultTokenProvider.java:114) at com.ibm.cloud.objectstorage.client.builder.AwsClientBuilder.withIAMEndpoint(AwsClientBuilder.java:166) at 

Rollbacking to the previous version without this change (2.9.1) gave the correct error message : 
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1964)
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:328)
at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:322)
at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1614)
at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
at sun.security.ssl.Handshaker.processLoop(Handshaker.java:1052)
at sun.security.ssl.Handshaker.process_record(Handshaker.java:987)
at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1072)
at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
at com.ibm.cloud.objectstorage.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:133)
at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
at com.ibm.cloud.objectstorage.oauth.DefaultTokenProvider.retrieveToken(DefaultTokenProvider.java:154)

**Comment by IBMeric** [comment]
Thanks for your report. Someone is looking at this now.

**Comment by IBMeric** [comment]
@ifs-gaetanlalanne This issue has been resolved in 2.11.1. Please verify and close this ticket.

**Comment by ifs-gaetanlalanne** [comment]
Fixed ! Thank you 👯
