### ISSUE TITLE
Need assistance to understand AmazonS3Exception: Null token returned by the Token Provider

### ISSUE THREAD

**Issue by vrangana** [IBM/ibm-cos-sdk-java#47]
Hi Team,

Can help me understand the scenario when the following AmazonS3Exception is raised with status code as '0'. Thanks in advance.

```
2022-01-18 03:19:33 INFO  [main] CosBucketObjectMonitor:219 checkForRetryException - Retrying for exception:
com.ibm.cloud.objectstorage.services.s3.model.AmazonS3Exception: Null token returned by the Token Provider (Service: IAM; Status Code: 0; Error Code: null; Request ID: null), S3 Extended Request ID: null
        at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.retrieveToken(DefaultTokenManager.java:394)
        at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.getToken(DefaultTokenManager.java:200)
        at com.ibm.cloud.objectstorage.oauth.IBMOAuthSigner.sign(IBMOAuthSigner.java:64)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1271)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 77 more
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4148)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4095)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4089)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:836)
        at com.ibm.wsc.infohub.monitor.cos.CosBucketObjectMonitor.lambda$getListObjectsV2Result$6(CosBucketObjectMonitor.java:181)
        at <unknown class>.call(Unknown Source)
        at net.jodah.failsafe.Functions$11.call(Functions.java:263)
        at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
        at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:69)
        at com.ibm.wsc.infohub.monitor.cos.CosBucketObjectMonitor.getListObjectsV2Result(CosBucketObjectMonitor.java:179)
        at com.ibm.wsc.infohub.monitor.cos.CosBucketObjectMonitor.lambda$getUnprocessedObjects$4(CosBucketObjectMonitor.java:94)
        at <unknown class>.accept(Unknown Source)
        at java.base/java.util.HashMap.forEach(Unknown Source)
        at com.ibm.wsc.infohub.monitor.cos.CosBucketObjectMonitor.getUnprocessedObjects(CosBucketObjectMonitor.java:81)
        at com.ibm.wsc.infohub.monitor.cos.CosImportMonitorRunner.queueNewBucketObjectsForTenants(CosImportMonitorRunner.java:213)
        at com.ibm.wsc.infohub.monitor.cos.CosImportMonitorRunner.monitorNewBucketObjectsForTenant(CosImportMonitorRunner.java:199)
        at com.ibm.wsc.infohub.monitor.cos.CosImportMonitorRunner.execute(CosImportMonitorRunner.java:140)
        at com.ibm.wsc.infohub.monitor.cos.CosImportMonitorRunner.run(CosImportMonitorRunner.java:98)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
        at com.ibm.wsc.infohub.monitor.CosImportNewObjectScannerApplication.main(CosImportNewObjectScannerApplication.java:24)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
javax.net.ssl.SSLHandshakeException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.ssl.Alert.createSSLException(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.fatal(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.onConsumeCertificate(Unknown Source)
        at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.consume(Unknown Source)
        at java.base/sun.security.ssl.SSLHandshake.consume(Unknown Source)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.TransportContext.dispatch(Unknown Source)
        at java.base/sun.security.ssl.SSLTransport.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(Unknown Source)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at com.ibm.cloud.objectstorage.http.conn.ssl.SdkTLSSocketFactory.connectSocket(SdkTLSSocketFactory.java:133)
        at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:56)
        at com.ibm.cloud.objectstorage.oauth.DefaultTokenProvider.retrieveToken(DefaultTokenProvider.java:154)
        at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.retrieveToken(DefaultTokenManager.java:381)
        at com.ibm.cloud.objectstorage.oauth.DefaultTokenManager.getToken(DefaultTokenManager.java:200)
        at com.ibm.cloud.objectstorage.oauth.IBMOAuthSigner.sign(IBMOAuthSigner.java:64)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1271)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1113)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:770)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:744)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:726)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:686)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:668)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:532)
        at com.ibm.cloud.objectstorage.http.AmazonHttpClient.execute(AmazonHttpClient.java:512)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4148)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4095)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:4089)
        at com.ibm.cloud.objectstorage.services.s3.AmazonS3Client.listObjectsV2(AmazonS3Client.java:836)
        at com.ibm.wsc.infohub.monitor.cos.CosBucketObjectMonitor.lambda$getListObjectsV2Result$6(CosBucketObjectMonitor.java:181)
        at <unknown class>.call(Unknown Source)
        at net.jodah.failsafe.Functions$11.call(Functions.java:263)
        at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:145)
        at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:69)
        at com.ibm.wsc.infohub.monitor.cos.CosBucketObjectMonitor.getListObjectsV2Result(CosBucketObjectMonitor.java:179)
        at com.ibm.wsc.infohub.monitor.cos.CosBucketObjectMonitor.lambda$getUnprocessedObjects$4(CosBucketObjectMonitor.java:94)
        at <unknown class>.accept(Unknown Source)
        at java.base/java.util.HashMap.forEach(Unknown Source)
        at com.ibm.wsc.infohub.monitor.cos.CosBucketObjectMonitor.getUnprocessedObjects(CosBucketObjectMonitor.java:81)
        at com.ibm.wsc.infohub.monitor.cos.CosImportMonitorRunner.queueNewBucketObjectsForTenants(CosImportMonitorRunner.java:213)
        at com.ibm.wsc.infohub.monitor.cos.CosImportMonitorRunner.monitorNewBucketObjectsForTenant(CosImportMonitorRunner.java:199)
        at com.ibm.wsc.infohub.monitor.cos.CosImportMonitorRunner.execute(CosImportMonitorRunner.java:140)
        at com.ibm.wsc.infohub.monitor.cos.CosImportMonitorRunner.run(CosImportMonitorRunner.java:98)
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:782)
        at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:772)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:345)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332)
        at com.ibm.wsc.infohub.monitor.CosImportNewObjectScannerApplication.main(CosImportNewObjectScannerApplication.java:24)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.validator.PKIXValidator.doBuild(Unknown Source)
        at java.base/sun.security.validator.PKIXValidator.engineValidate(Unknown Source)
        at java.base/sun.security.validator.Validator.validate(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.validate(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(Unknown Source)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(Unknown Source)
        ... 71 more
Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.build(Unknown Source)
        at java.base/sun.security.provider.certpath.SunCertPathBuilder.engineBuild(Unknown Source)
        at java.base/java.security.cert.CertPathBuilder.build(Unknown Source)
        ... 77 more
```

**Comment by IBMeric** [comment]
This error was confusing and has since been changed. The IAM token code has two classes that work together, `TokenManager` and `TokenProvider`. `TokenManager` maintains non-expired tokens for HTTP requests. `TokenProvider` retrieves tokens from the IAM server when `TokenManager` requests a new one. Originally, when `TokenProvider` had a problem, it ate the relevant exception, and returned `null` to `TokenManager`. `TokenManager` would check for this and then throw the above exception. No status code was used, so the exception defaulted to zero. Details of the actual problem, almost certainly network related, were unfortunately lost.

Starting from 2.10.1, this exception has been eliminated. We refactored `TokenProvider` to no longer eat important exceptions. You should now have the necessary details to investigate the problem. I recommend you upgrade to the latest version (2.11.1 just came out today) and see if you run into the same failure scenario again.

If this doesn't answer your question, please let me know. Otherwise, please close the ticket.

**Comment by IBMeric** [comment]
Closing ticket as resolved.
